# ----- Autogenerated: Sensor imports -----


from sensor_msgs.msg import Image



from nav_msgs.msg import Odometry
from sensor_msgs.msg import BatteryState, Imu, NavSatFix

# Import custom message for master to sensing drone communication
from aerocluster_msgs.msg import MasterCommand
from aerocluster_msgs.msg import MasterBroadcast


# -----------------------------------------
import cv2
from cv_bridge import CvBridge
import ast
import time
from std_msgs.msg import String

from as2_python_api.drone_interface import DroneInterface
from as2_python_api.modules.motion_reference_handler_module import MotionReferenceHandlerModule

import sys
import csv

import os
import uuid
import rclpy
from rclpy.node import Node
from rclpy.executors import MultiThreadedExecutor
from rclpy.callback_groups import ReentrantCallbackGroup, MutuallyExclusiveCallbackGroup
from rclpy.qos import QoSProfile, QoSReliabilityPolicy, QoSHistoryPolicy




class AeroClusterMaster(Node):
    """
    Sensing drone in the AeroCluster orchestration.
    """
    def __init__(self):
        super().__init__("aerocluster_main")

        self.my_ID = 0
        self.current_master = 0
        self.total_drones_in_fleet = 5

        self.health_status = {}
        self.health_order_to_publish = []
        self.absent_counter = {i: 0 for i in range(1, self.total_drones_in_fleet)}
        self.health_score = {}
        self.battery_req_to_return = 10

        self.current_battery = 100
        self.total_compute = 7.2
        self.dnn_load = 1

        self.model_stored = {'obstacle':{'caller_func':'obstacle_avoidance', 'mem_req':2, 'avg_inf_time':200}, 'monodepth':{'monodepth_estimation':'dnn_func_name2', 'mem_req':2, 'avg_inf_time':200}, 'master_model':{'caller_func':'master_analytics', 'mem_req':2, 'avg_inf_time':200}}
        self.model_running = ['master_model']

        self.all_drones = set(range(1, self.total_drones_in_fleet))
        self.present_drones = set()
        self.absent_drones = set()

        self.stored_model_drone_map = {}
        self.drone_running_model_map = {}
        self.model_to_memory_map = {}
        self.model_to_inf_time_map = {}

        self.ns = "drone"+str(self.my_ID)
        self.drone = DroneInterface(self.ns, verbose=True)

        self.drone.arm()
        self.drone.offboard()

        qos_profile = QoSProfile(
            reliability=QoSReliabilityPolicy.BEST_EFFORT,  # Match publisher's QoS
            history=QoSHistoryPolicy.KEEP_LAST,
            depth=10
        )

        # Create publisher to publish master commands
        self.command_publisher = self.create_publisher(MasterCommand, "/master/command", 10)
        self.health_publisher = self.create_publisher(String, "/master/health", 10)
        self.reassign_publisher = self.create_publisher(MasterBroadcast, "/master/msg", 10)

        # Create subscription to receive health messages from other slave drones
        self.create_subscription(String, "/slave/health", self.health_cb, qos_profile, callback_group=MutuallyExclusiveCallbackGroup())
        self.create_subscription(String, "/slave/model", self.slave_model_cb, qos_profile, callback_group=MutuallyExclusiveCallbackGroup())
        self.create_subscription(String, "/slave/msg", self.process_slave_msg, qos_profile, callback_group=MutuallyExclusiveCallbackGroup())

        self.start_logging = True

        self.file_battery = open(f"/root/aerodaas_mounted/ssds/{self.ns}/battery_data.csv", "w", newline="")
        self.file_odom = open(f"/root/aerodaas_mounted/ssds/{self.ns}/odom_data.csv", "w", newline="")
        self.file_imu = open(f"/root/aerodaas_mounted/ssds/{self.ns}/imu_data.csv", "w", newline="")
        self.file_gps = open(f"/root/aerodaas_mounted/ssds/{self.ns}/gps_data.csv", "w", newline="")

        self.csv_writer_battery = csv.writer(self.file_battery)
        self.csv_writer_odom = csv.writer(self.file_odom)
        self.csv_writer_imu = csv.writer(self.file_imu)
        self.csv_writer_gps = csv.writer(self.file_gps)

        # Write headers if the file is empty
        if self.file_battery.tell() == 0:
            self.csv_writer_battery.writerow(["timestamp", "battery"])
            self.file_battery.flush()
        
        if self.file_odom.tell() == 0:
            self.csv_writer_odom.writerow([
                "timestamp", "pose_x", "pose_y", "pose_z",
                "orientation_x", "orientation_y", "orientation_z", "orientation_w",
                "twist_linear_x", "twist_linear_y", "twist_linear_z",
                "twist_angular_x", "twist_angular_y", "twist_angular_z"
            ])
            self.file_odom.flush()

        if self.file_imu.tell() == 0:
            self.csv_writer_imu.writerow([
                "timestamp",
                "orientation_x", "orientation_y", "orientation_z", "orientation_w",
                "angular_velocity_x", "angular_velocity_y", "angular_velocity_z",
                "linear_acceleration_x", "linear_acceleration_y", "linear_acceleration_z"
            ])
            self.file_imu.flush()
        
        if self.file_gps.tell() == 0:
            self.csv_writer_gps.writerow([
                "timestamp", "latitude", "longitude", "altitude"
            ])
            self.file_gps.flush()

        self.odom_idx = 0
        self.create_subscription(Odometry, f"/{self.ns}/sensor_measurements/odom", self.odom_cb, qos_profile, callback_group=MutuallyExclusiveCallbackGroup())
        self.create_subscription(BatteryState, f"/{self.ns}/sensor_measurements/battery", self.battery_cb, qos_profile, callback_group=MutuallyExclusiveCallbackGroup())
        self.create_subscription(Imu, f"/{self.ns}/sensor_measurements/imu", self.imu_cb, qos_profile, callback_group=MutuallyExclusiveCallbackGroup())
        self.create_subscription(NavSatFix, f"/{self.ns}/sensor_measurements/gps", self.gps_cb, qos_profile, callback_group=MutuallyExclusiveCallbackGroup())


        self.drone_motion_controller = MotionReferenceHandlerModule(drone=self.drone)

        self.start_mission()

        self.callback_counter = 1
        
        self.nav_timer = self.create_timer(15, self.timer_nav_callback)
        self.timer_publish_health = self.create_timer(10, self.publish_health_order)
       
    
    def start_mission(self):
        msg = {}
        msg['function'] = "rc"
        msg['type'] = "takeoff"
        msg['speed'] = 1.0
        msg['x'] = 0.0
        msg['y'] = 0.0
        msg['z'] = 1.5
        msg['yaw'] = 0.0
        msg['height'] = 1.5
        msg['lat'] = 0.0
        msg['longitude'] = 0.0
        
        self.publish_master_command(msg)

        self.drone.takeoff(height=1.5, speed=1.0)
        self.drone.go_to(x=0.0, y=0.0, z=1.5, frame_id="earth", speed=1.0)

    def timer_nav_callback(self):
        msg = {}
        if self.callback_counter % 4 == 1:
            msg['function'] = "rc"
            msg['type'] = "move"
            msg['speed'] = 1.0
            msg['x'] = 10.0
            msg['y'] = 0.0
            msg['z'] = 1.5
            msg['yaw'] = 0.0
            msg['height'] = 1.5
            msg['lat'] = 0.0
            msg['longitude'] = 0.0
        elif self.callback_counter % 4 == 2:
            msg['function'] = "rc"
            msg['type'] = "move"
            msg['speed'] = 1.0
            msg['x'] = 10.0
            msg['y'] = 10.0
            msg['z'] = 1.5
            msg['yaw'] = 0.0
            msg['height'] = 1.5
            msg['lat'] = 0.0
            msg['longitude'] = 0.0
        elif self.callback_counter % 4 == 3:
            msg['function'] = "rc"
            msg['type'] = "move"
            msg['speed'] = 1.0
            msg['x'] = 0.0
            msg['y'] = 10.0
            msg['z'] = 1.5
            msg['yaw'] = 0.0
            msg['height'] = 1.5
            msg['lat'] = 0.0
            msg['longitude'] = 0.0
        else:
            msg['function'] = "rc"
            msg['type'] = "move"
            msg['speed'] = 1.0
            msg['x'] = 0.0
            msg['y'] = 0.0
            msg['z'] = 1.5
            msg['yaw'] = 0.0
            msg['height'] = 1.5
            msg['lat'] = 0.0
            msg['longitude'] = 0.0
        
        self.callback_counter+=1
        self.publish_master_command(msg)
        goal = [msg["x"], msg["y"], msg["z"]]
        speed = msg["speed"]
        
        self.drone.go_to.go_to_point_path_facing(goal, speed=speed)

    
    
    def odom_cb(self, data):
        self.odom_idx += 1

        if not self.start_logging:
            return

        # if self.odom_idx % 10 != 0:
        #     return

        timestamp = data.header.stamp.sec

        pose = data.pose.pose.position
        pose_x = pose.x
        pose_y = pose.y
        pose_z = pose.z

        orientation = data.pose.pose.orientation
        orientation_x = orientation.x
        orientation_y = orientation.y
        orientation_z = orientation.z
        orientation_w = orientation.w

        twist_linear = data.twist.twist.linear
        twist_linear_x = twist_linear.x
        twist_linear_y = twist_linear.y
        twist_linear_z = twist_linear.z

        twist_angular = data.twist.twist.angular
        twist_angular_x = twist_angular.x
        twist_angular_y = twist_angular.y
        twist_angular_z = twist_angular.z

        self.csv_writer_odom.writerow([
            timestamp, pose_x, pose_y, pose_z,
            orientation_x, orientation_y, orientation_z, orientation_w,
            twist_linear_x, twist_linear_y, twist_linear_z,
            twist_angular_x, twist_angular_y, twist_angular_z
        ])

        self.file_odom.flush()

    def battery_cb(self, data):
        percentage = data.percentage
        timestamp = data.header.stamp.sec

        self.csv_writer_battery.writerow([timestamp, percentage])
        self.file_battery.flush()

    def imu_cb(self, data):
        if not self.start_logging:
            return

        # self.get_logger().info("---------- IMU -------------")
        # self.get_logger().info(data)
        # self.get_logger().info("-----------------------")

        timestamp = data.header.stamp.sec

        orientation = data.orientation
        orientation_x = orientation.x
        orientation_y = orientation.y
        orientation_z = orientation.z
        orientation_w = orientation.w

        angular_velocity = data.angular_velocity
        angular_velocity_x = angular_velocity.x
        angular_velocity_y = angular_velocity.y
        angular_velocity_z = angular_velocity.z

        linear_acceleration = data.linear_acceleration
        linear_acceleration_x = linear_acceleration.x
        linear_acceleration_y = linear_acceleration.y
        linear_acceleration_z = linear_acceleration.z

        self.csv_writer_imu.writerow([
            timestamp, orientation_x, orientation_y, orientation_z, orientation_w,
            angular_velocity_x, angular_velocity_y, angular_velocity_z,
            linear_acceleration_x, linear_acceleration_y, linear_acceleration_z
        ])

        self.file_imu.flush()

    def gps_cb(self, data):
        if not self.start_logging:
            return

        # self.get_logger().info("---------- GPS -------------")
        # self.get_logger().info(data)
        # self.get_logger().info("-----------------------")

        timestamp = data.header.stamp.sec

        latitude = data.latitude
        longitude = data.longitude
        altitude = data.altitude

        self.csv_writer_gps.writerow([
            timestamp, latitude, longitude, altitude
        ])
        
        self.file_gps.flush()
    

    # -------------------------------------------------------------------------
    # ---------------------- GFS Functions and Callbacks ----------------------

    def process_slave_msg(self, message):
        self.get_logger().info(f"Received slave msg : {message.data}")
        lst = message.data.split(";")
        sender_id = int(lst[0])
        if sender_id not in self.all_drones:
            return
        if lst[1]=="ack":
            if lst[2] == "OK":
                self.drone_running_model_map[sender_id].append(lst[3])

    def reassignModelDrone(self, drone_id):
        self.get_logger().info("INSIDE REASSIGNMENT")

        running_models_on_crashed_drone = self.drone_running_model_map[drone_id]
        _ = self.drone_running_model_map.pop(drone_id)
        for model in running_models_on_crashed_drone:
            if drone_id in self.stored_model_drone_map[model]:
                if len(self.stored_model_drone_map[model]) == 1:
                    _ = self.stored_model_drone_map.pop(model)
                else:
                    self.stored_model_drone_map[model].remove(drone_id)
        
        reassignment_map = {}
        unavailable_model = []
        for model in running_models_on_crashed_drone:
            # check for existence of model and return a list (make a func)
            # get health, battery and avail_mem
            # filter out drone with less avail_mem than required model_mem
            # if a drone satisfies all the condition then go ahead and publish
            # after publishing create a timer to check for ack (only if we can stop timer)
            if model not in self.stored_model_drone_map:
                unavailable_model.append(model)
            else:
                avail_drones = self.stored_model_drone_map[model]
                best_drone = None
                best_health = 0
                mem_req = self.model_to_memory_map[model]
                for drone in avail_drones:
                    if model not in self.drone_running_model_map[drone] and self.health_status[drone]['battery'] >= self.battery_req_to_return and mem_req <= 0.3 + self.health_status[drone]['avail_mem']:  # 0.3 buffer RAM
                        health = self.health_score[drone]
                        if health>best_health:
                            best_drone = drone
                            best_health = health
                if best_drone:
                    reassignment_map[model]=best_drone
        
        self.get_logger().info(f"Reassignment Map : {reassignment_map}")
        
        for model,targetID in reassignment_map.items():
            msg = MasterBroadcast()
            msg.id = self.my_ID
            msg.target_id = targetID
            msg.msg = f"run;{model}"
            self.get_logger().info(f"Publishing Reassignment to slave {msg.target_id} : {msg.msg}")
            self.reassign_publisher.publish(msg)

    def slave_model_cb(self, message):
        self.get_logger().info(f"Received Slave Models : {message.data}")
        lst = message.data.split(";")
        drone_id = int(lst[0])
        if drone_id not in self.all_drones:
            return
        current_model_stored = eval(lst[1])
        current_model_running = eval(lst[2])

        # make a dictionary in init
        # model to drone mapping, e.g., {'obstacle':[0,1]}
        # drone to runnning model mapping, e.g., {'1':['obstacle']}

        for key in current_model_stored.keys():
            if key in self.stored_model_drone_map:
                self.stored_model_drone_map[key].append(drone_id)
            else:
                self.stored_model_drone_map[key] = [drone_id]
                model_details = current_model_stored[key]
                self.model_to_memory_map[key] = model_details['mem_req']
                self.model_to_inf_time_map[key] = model_details['avg_inf_time']

        self.drone_running_model_map[drone_id] = current_model_running

    # Sending health data
    def health_cb(self, message):
        self.get_logger().info(f"Received : {message.data}")
        lst = message.data.split(";")
        drone_id = int(lst[0])
        if drone_id not in self.all_drones:
            return
        battery = int(lst[1])
        avail_mem = float(lst[2])
        total_compute = float(lst[3])
        self.health_status[drone_id] = {'battery':battery, 'avail_mem':avail_mem, 'total_compute':total_compute}
        self.present_drones.add(drone_id)
    
    def publish_health_order(self):
        self.get_logger().info("="*20)
        self.get_logger().info(f"Current All Drones : {self.all_drones}")
        self.get_logger().info(f"Current Present Drones : {self.present_drones}")
        self.get_logger().info(f"Previous Absent Drones : {self.absent_drones}")
        self.get_logger().info(f"Previous Absent Counter : {self.absent_counter}")
        self.get_logger().info("="*20)
        crashed_drones = []
        if self.total_drones_in_fleet == 1:
            self.get_logger().info("All drones down...ABORT MISSION!!!")
            self.land()
        if len(self.present_drones) != self.total_drones_in_fleet - 1:
            self.absent_drones = self.all_drones - self.present_drones
            for drone_id in self.absent_drones:
                self.absent_counter[drone_id] += 1
                if drone_id in self.health_status:
                    self.health_status[drone_id]['battery'] = 0
            for drone_id in self.present_drones:
                self.absent_counter[drone_id] = 0
            
            self.get_logger().info(f"Updated Absent Counter : {self.absent_counter}")

            # remove a drone from fleet if health isn't received in last 2 intervals
            for drone_id, counter in self.absent_counter.items():
                if counter > 1:
                    self.get_logger().info(f"Removing drone : {drone_id}")
                    self.all_drones.remove(drone_id)
                    self.total_drones_in_fleet -= 1
                    if drone_id in self.health_status:
                        _ = self.health_status.pop(drone_id)
                        _ = self.health_score.pop(drone_id)
                    crashed_drones.append(drone_id)

        if len(self.present_drones) == 0:
            return
        
        for drone_id in self.present_drones:
            self.absent_counter[drone_id] = 0
        
        # 1. Find the maximum total RAM across all drones
        max_total_ram = max(drone['total_compute'] for drone in self.health_status.values())

        # 2. Calculate health for each drone
        for drone_id, status in self.health_status.items():
            battery = status['battery']
            avail_mem = status['avail_mem']
            health = (battery + (avail_mem / max_total_ram) * 100) / 2
            self.health_score[drone_id] = health
        
        # 3. Sort drones by health in descending order
        sorted_health_data = sorted(self.health_score.items(), key=lambda x: x[1], reverse=True)
        
        self.get_logger().info(f"Current Health Status : {self.health_status}")

        # 4. Extract only the sorted drone IDs
        sorted_drone_ids = [self.my_ID] + [drone_id for drone_id, _ in sorted_health_data]

        msg = String()
        msg.data = str(sorted_drone_ids)
        self.get_logger().info(f"Publishing health order to slaves -> {sorted_drone_ids}")
        self.health_publisher.publish(msg)

        self.present_drones.clear()

        for drone in crashed_drones:
            _ = self.absent_counter.pop(drone)
            self.reassignModelDrone(drone)
    

    # Processing the commands from master drone
    def publish_master_command(self, command_dict):
        """
            The message contains following fields:

            # MasterCommand.msg
            int32 id              # Unique command ID
            string function       # e.g. "takeoff", "navigate", etc.
            string type           # Command type or category
            float64 speed         # Target speed in m/s
            float64 x             # Local frame X coordinate
            float64 y             # Local frame Y coordinate
            float64 z             # Local frame Z coordinate
            float64 yaw           # Desired yaw angle in radians
            float64 height        # Target altitude in meters
            float64 lat           # GPS latitude (WGS84)
            float64 longitude     # GPS longitude (WGS84)            
        """

        message = MasterCommand()
        message.id = self.my_ID
        message.function = command_dict['function']
        message.type = command_dict["type"]
        message.speed = command_dict["speed"]
        message.x = command_dict["x"]
        message.y = command_dict["y"]
        message.z = command_dict["z"]
        message.yaw = command_dict["yaw"]
        message.height = command_dict["height"]
        message.lat = command_dict["lat"]
        message.longitude = command_dict["longitude"]

        self.get_logger().info(f"Publishing master command to slave ...")
        self.command_publisher.publish(message)


    def drone_navigation(self, command):
        """
        Autogenerated: Handles navigation commands for the drone.
        """
        if command["type"] == "takeoff":
            self.drone.takeoff(height=command["height"], speed=command["speed"])
        elif command["type"] == "land":
            self.drone.land(speed=command["speed"])
        elif command["type"] == "move":
            goal = [command["x"], command["y"], command["z"]]
            speed = command["speed"]
            
            # self.drone.go_to.go_to_point(goal, speed=speed)
            self.drone.go_to.go_to_point_path_facing(goal, speed=speed)
            # self.drone.go_to(x=command["x"], y=command["y"], z=command["z"], speed=speed)
        elif command["type"] == "goto":
            goal = [command["lat"], command["long"]]
            speed = command["speed"]

            self.drone.go_to.go_to_gps_point(goal, speed=speed)
            # self.drone.go_to.go_to_gps_point_path_facing(goal, speed=speed)
        elif command["type"] == "velocity":
            fb = int(command["x"])/100
            lr = int(command["y"])/100
            ud = int(command["z"])/100
            yaw = -int(command["yaw"])/100
            
            self.drone_motion_controller.speed.send_speed_command_with_yaw_speed([fb/2, lr, ud/2], twist_frame_id=f"{self.ns}/base_link", yaw_speed=yaw/2)
    
    def land(self):
        self.drone.land(0.5)
        
        self.file_battery.close()
        self.file_odom.close()
        self.file_imu.close()
        self.file_gps.close()
        
        

def main(args=None):
    rclpy.init(args=args)

    node = AeroClusterMaster()
    executor = MultiThreadedExecutor()
    executor.add_node(node)

    try:
        node.get_logger().info("AeroCluster main node starting")
        executor.spin()
    except KeyboardInterrupt:
        node.land()
        node.get_logger().info("Shutting down")
    
    node.destroy_node()
    rclpy.shutdown()


if __name__ == "__main__":
    main()
